apiVersion: v1
kind: Service
metadata:
  name: emmanuel-services
spec:
  type: {{ .Values.service.type }}
  selector:
    app: emmanuel-services
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80

